STORAGE_BACKEND: "local"
LS_INPUT_PATH: "validation_data/log_anomaly_detector-100000-events.json"
LS_OUTPUT_PATH: "validation_data/local-results-1.txt"
INFER_ANOMALY_THRESHOLD: 1.3
INFER_TIME_SPAN: 1
INFER_LOOPS: 1
PARALLELISM: 6
