---
lad_app_name: "log-anomaly-detector"
lad_git_uri: "https://github.com/AICoE/log-anomaly-detector.git"
lad_git_ref: "master"
lad_image_name: "log-anomaly-detector-image"
lad_pvc_size: "1Gi"
lad_container_cpu_limit: "1"
lad_container_memory_limit: "1Gi"
# Update the elasticsearch host and factstore url before deploying
lad_factstore_url: "http://URLTOFACTSTORE.com/"
lad_elasticsearch_url: "lad-elasticsearch-service.{{ namespace }}.svc:9200"
lad_app_config: |
  STORAGE_DATASOURCE: "es.source"
  STORAGE_DATASINK: "es.sink"
  ES_ENDPOINT: "{{ lad_elasticsearch_url }}"
  ES_QUERY: 'ecommerce'
  ES_USE_SSL: False
  ES_INPUT_INDEX: "lad-"
  ES_TARGET_INDEX: "odcs-anomaly-detect-"
  ES_VERSION: 7
  FACT_STORE_URL: "{{ lad_factstore_url }}"
  INFER_ANOMALY_THRESHOLD: 1.3
  INFER_TIME_SPAN: 10
  INFER_LOOPS: 1
  PARALLELISM: 6
  SOMPY_TRAIN_ROUGH_LEN: 100
  SOMPY_TRAIN_FINETUNE_LEN: 5
  SOMPY_INIT: "random"
