---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: "{{ grafana.app_name }}"
  labels:
    deploymentConfig: "{{ grafana.app_name }}"
    app: "{{ grafana.app_name }}"
spec:
  replicas: 1
  selector:
    deploymentConfig: "{{ grafana.app_name }}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentConfig: "{{ grafana.app_name }}"
        app: "{{ grafana.app_name }}"
    spec:
      containers:
        - name: "{{ grafana.app_name }}"
          image: "{{ grafana.container_image }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: '1'
              memory: "{{ grafana.container_memory_limit }}"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ grafana.app_name }}-service"
  labels:
    app: "{{ grafana.app_name }}"
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: "{{ grafana.app_name }}"

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ grafana.app_name }}-route"
  labels:
    app: "{{ grafana.app_name }}"
spec:
  to:
    kind: Service
    name: "{{ grafana.app_name }}-service"
