---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: "{{ mysql.database_service_name }}"
  name: "{{ mysql.database_service_name }}"
stringData:
  database-name: "{{ mysql.mysql_database }}"
  database-password: "{{ mysql.mysql_password }}"
  database-root-password: "{{ mysql.mysql_root_password }}"
  database-user: "{{ mysql.mysql_user }}"

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mysql")].port}
  labels:
    app: "{{ mysql.database_service_name }}"
  name: "{{ mysql.database_service_name }}"
spec:
  ports:
    - name: mysql
      port: "{{ mysql.mysql_service_port }}"
  selector:
    name: "{{ mysql.database_service_name }}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: "{{ mysql.database_service_name }}"
  name: "{{ mysql.database_service_name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ mysql.volume_capacity }}"

---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
  labels:
    app: "{{ mysql.database_service_name }}"
  name: "{{ mysql.database_service_name }}"
spec:
  replicas: 1
  selector:
    name: "{{ mysql.database_service_name }}"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: "{{ mysql.database_service_name }}"
    spec:
      containers:
        - env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: "{{ mysql.database_service_name }}"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: "{{ mysql.database_service_name }}"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-root-password
                  name: "{{ mysql.database_service_name }}"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: "{{ mysql.database_service_name }}"
          image: " "
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: {{mysql.mysql_service_port}}
            timeoutSeconds: 1
          name: mysql
          ports:
            - containerPort: "{{ mysql.mysql_service_port }}"
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - MYSQL_PWD="{{ mysql.mysql_password }}" /opt/rh/rh-mysql{{ mysql.mysql_version | replace('.', '') }}/root/usr/bin/mysql
                  -h 127.0.0.1 -u {{ mysql.mysql_user }} -D {{ mysql.mysql_database }}
                  -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: "{{ mysql.memory_limit }}"
          volumeMounts:
            - mountPath: "/var/lib/mysql/data"
              name: "{{ mysql.database_service_name }}-data"
      volumes:
        - name: "{{ mysql.database_service_name }}-data"
          persistentVolumeClaim:
            claimName: "{{ mysql.database_service_name }}"
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - mysql
        from:
          kind: ImageStreamTag
          name: mysql:{{ mysql.mysql_version }}
          namespace: "openshift"
      type: ImageChange
    - type: ConfigChange
