---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: "{{ es.app_name }}"
  labels:
    deploymentConfig: "{{ es.app_name }}"
    app: "{{ es.app_name }}"
spec:
  replicas: 1
  selector:
    deploymentConfig: "{{ es.app_name }}"
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        deploymentConfig: "{{ es.app_name }}"
        app: "{{ es.app_name }}"
    spec:
      containers:
        - env:
            - name: "discovery.type"
              value: "{{ es.discovery_type }}"
          name: "{{ es.app_name }}"
          image: "{{ es.image_name }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "{{ es.container_cpu_limit }}"
              memory: "{{ es.container_memory_limit }}"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ es.app_name }}"
  labels:
    app: "{{ es.app_name }}"
spec:
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: es-comm
  selector:
    app: "{{ es.app_name }}"

---
apiVersion: v1
kind: Route
metadata:
  name: "{{ es.app_name }}"
  labels:
    app: "{{ es.app_name }}"
    component: factstore
    customer: "{{ common.customer_id }}"
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: "{{ es.app_name }}"
