---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: "{{ lad.app_name }}"
  name: "{{ lad.app_name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ lad.pvc_size }}"

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ lad.app_name }}"
  name: "{{ lad.app_name }}"
spec:
  replicas: 0
  selector:
    deploymentconfig: "{{ lad.app_name }}"
  template:
    metadata:
      labels:
        app: "{{ lad.app_name }}"
        deploymentconfig: "{{ lad.app_name }}"
    spec:
      containers:
        - args:
            - app.py
            - run
            - --config-yaml
            - validation_data/.env_config.yaml
          command:
            - python
          image: "{{ lad.app_name }}:latest"
          imagePullPolicy: Always
          name: log-anomaly-detector
          resources:
            limits:
              cpu: "{{ lad.container_cpu_limit }}"
              memory: "{{ lad.container_memory_limit }}"
          volumeMounts:
            - mountPath: /opt/app-root/src/models
              name: model-storage
            - mountPath: /opt/app-root/src/validation_data
              name: lad-config-volume
            - mountPath: /opt/app-root/src/certs
              name: es-certs
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - claimName: "{{ lad.app_name }}"
          name: model-storage
          persistentVolumeClaim: null
        - name: es-certs
          secret:
            defaultMode: 420
            secretName: "{{ lad.es_secrets_name }}"
        - configMap:
            defaultMode: 420
            name: "{{ lad.app_name }}"
          name: lad-config-volume
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - log-anomaly-detector
        from:
          kind: ImageStreamTag
          name: "{{ ladbuild.app_name }}:latest"
      type: ImageChange

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ lad.app_name }}"
  labels:
    app: "{{ lad.app_name }}"
    monitor: "True"
spec:
  selector:
    app: "{{ lad.app_name }}"
  ports:
    - protocol: TCP
      name: metrics
      port: 8080
      targetPort: 8080
