{
 "title": "Log_anomaly_detector_dashboard-0.0.1 Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Log Entries Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_loglines_count{job=\"log-anomaly-detector-greenwave\"}"
    }
   ]
  },
  {
   "title": "False Positive Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "aiops_lad_inference_count_total{job=\"log-anomaly-detector-greenwave\"}"
    }
   ]
  },
  {
   "title": "Feedback Count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_human_feedback_count_total{anomaly_status=\"False\",customer_id=\"greenwave\",job=\"log-anomaly-detector-greenwave-factstore\"}",
     "legendFormat": "{{Feedback count}}"
    }
   ]
  },
  {
   "title": "Anomaly vs Regular Logs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"0\",job=\"log-anomaly-detector-greenwave\"}\n",
     "legendFormat": "Normal Log"
    },
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"1\",job=\"log-anomaly-detector-greenwave\"}",
     "legendFormat": "Anomaly Log"
    }
   ]
  },
  {
   "title": "Total Anomaly",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"1\", job=\"log-anomaly-detector-greenwave\"}"
    }
   ]
  },
  {
   "title": "Total Training Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_train_count_total{job=\"log-anomaly-detector-greenwave\"}"
    }
   ]
  },
  {
   "title": "Threshold Value",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "aiops_lad_threshold{job=\"log-anomaly-detector-greenwave\"}"
    }
   ]
  },
  {
   "title": "Anomaly Score",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(aiops_lad_anomaly_avg_score)",
     "legendFormat": "Average Anomaly Score"
    },
    { "expr": "aiops_lad_threshold", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Rate in last 5 mins of logs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aiops_lad_loglines_count[5m])",
     "legendFormat": "log entries"
    }
   ]
  },
  {
   "title": "Rate Anomalies per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aiops_lad_anomaly_count{anomaly_status=\"0\",job=\"log-anomaly-detector-greenwave\"}[5m])",
     "legendFormat": "normal"
    },
    {
     "expr": "rate(aiops_lad_anomaly_count{anomaly_status=\"1\",job=\"log-anomaly-detector-greenwave\"}[5m])",
     "legendFormat": "anomaly"
    }
   ]
  },
  {
   "title": "Number of log lines processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"1\",job=\"log-anomaly-detector-greenwave\"}\n",
     "legendFormat": "Anomaly Log"
    },
    {
     "expr": "aiops_lad_anomaly_count{job=\"log-anomaly-detector-greenwave\"}\n",
     "legendFormat": "Anomaly Log"
    }
   ]
  },
  {
   "title": "num of lines injested",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aiops_lad_loglines_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Percentage of logs that are not anomalies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aiops_lad_anomaly_count{anomaly_status=\"0\",job=\"log-anomaly-detector-greenwave\"}[5m])\n",
     "legendFormat": "Anomaly Log"
    }
   ]
  },
  {
   "title": "Percentage of logs that are not anomalies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"0\"}\n",
     "legendFormat": "Normal Log"
    },
    {
     "expr": "aiops_lad_anomaly_count{anomaly_status=\"1\"}\n",
     "legendFormat": "Anomaly Log"
    }
   ]
  }
 ]
}