---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: "{{ factstore_app_name }}"
    component: factstore
    customer: "{{ factstore_customer_id }}"
  name: "{{ factstore_app_name }}"
spec:
  lookupPolicy:
    local: true

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: "{{ factstore_app_name }}"
    component: factstore
    customer: "{{ factstore_customer_id }}"
  name: "{{ factstore_app_name }}"
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "{{ factstore_app_name }}:latest"
  source:
    git:
      ref: "{{ factstore_git_ref }}"
      uri: "{{ factstore_git_uri }}"
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source
  triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: "{{ factstore_app_name }}"
    component: factstore
    customer: "{{ factstore_customer_id }}"
  name: "{{ factstore_app_name }}"
spec:
  replicas: 1
  selector:
    deploymentconfig: "{{ factstore_app_name }}"
  template:
    metadata:
      labels:
        app: "{{ factstore_app_name }}"
        component: factstore
        customer: "{{ factstore_customer_id }}"
        deploymentconfig: "{{ factstore_app_name }}"
    spec:
      containers:
        - args:
            - app.py
            - ui
          command:
            - python
          image: log-anomaly-detector-factstore:latest
          imagePullPolicy: Always
          name: log-anomaly-detector-factstore
          env:
            - name: SQL_CONNECT
              value: "{{ factstore_sql_connect }}"
            - name: CUSTOMER_ID
              value: "{{ factstore_customer_id }}"
          resources:
            limits:
              cpu: "{{ factstore_cpu_limit }}"
              memory: "{{ factstore_memory_limit }}"
            requests:
              cpu: 500m
              memory: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - log-anomaly-detector-factstore
        from:
          kind: ImageStreamTag
          name: "{{ factstore_app_name }}:latest"
      type: ImageChange

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ factstore_app_name }}"
  labels:
    app: "{{ factstore_app_name }}"
    component: factstore
    customer: "{{ factstore_customer_id }}"
spec:
  selector:
    app: "{{ factstore_app_name }}"
  ports:
    - port: 5001
      name: http

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ factstore_app_name }}-metrics"
  labels:
    app: "{{ factstore_app_name }}"
    component: factstore
    customer: "{{ factstore_customer_id }}"
spec:
  selector:
    app: "{{ factstore_app_name }}"
  ports:
    - port: 8080
      name: metrics

---
apiVersion: v1
kind: Route
metadata:
  name: "{{ factstore_app_name }}"
  labels:
    app: "{{ factstore_app_name }}"
    component: factstore
    customer: "{{ factstore_customer_id }}"
spec:
  to:
    kind: Service
    name: "{{ factstore_app_name }}"
