---
- name: Deploy MySQL Persistent DB to Openshift
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Load the common vars file
      include_vars:
        file: "vars/common-vars.yaml"

    - name: Load the lad vars file
      include_vars:
        file: "vars/mysql-vars.yaml"

    - name: Ensure that the required variables were found in the vars file
      fail:
        msg: "{{ item }} variable was not found in vars files"
      when: "{{ item }} is undefined"
      with_items:
        - namespace
        - kubeconfig
        - database_service_name
        - mysql_database
        - mysql_password
        - mysql_root_password
        - mysql_user
        - memory_limit
        - volume_capacity
        - mysql_version

    - name: Deploy the MySQL-Persistent objects to Openshift
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        namespace: "{{ namespace }}"
        verify_ssl: "no"
        definition: >-
          {{ lookup('template', 'mysql-persistent-objects.yaml') }}
