---
- name: Deploy Log Anomaly Detector to Openshift
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Load the common vars file
      include_vars:
        file: "vars/common-vars.yaml"

    - name: Load the lad vars file
      include_vars:
        file: "vars/lad-vars.yaml"

    - name: Ensure that the required variables were found in the vars file
      fail:
        msg: "{{ item }} variable was not found in vars files"
      when: "{{ item }} is undefined"
      with_items:
        - namespace
        - kubeconfig
        - lad_app_name
        - lad_git_uri

    - name: Update the configmap
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        namespace: "{{ namespace }}"
        verify_ssl: "no"
        api_version: v1
        definition:
          kind: ConfigMap
          metadata:
            name: "{{ lad_app_name }}"
            labels:
              app: "{{ lad_app_name }}"
          data:
            .env_config.yaml: "{{ lad_app_config }}"

    - name: Deploy the Log Anomaly Detector objects to Openshift
      k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        namespace: "{{ namespace }}"
        verify_ssl: "no"
        definition: >-
          {{ lookup('template', 'lad-openshift-objects.yaml') }}
